server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mysql://localhost:3306/laptopshop_identity
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
