server:
  port: 8888

app:
  prefix: /api/v1
  identity-service: http://localhost:8080
  file-service: http://localhost:8081
  product-service: http://localhost:8082
  inventory-service: http://localhost:8083
  order-service: http://localhost:8084
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-service
              uri: ${app.identity-service}
              predicates:
                - Path=${app.prefix}/identity/**
              filters:
                - StripPrefix=2
            - id: file-service
              uri: ${app.file-service}
              predicates:
                - Path=${app.prefix}/file/**
              filters:
                - StripPrefix=2
            - id: product-service
              uri: ${app.product-service}
              predicates:
                - Path=${app.prefix}/product/**
              filters:
                - StripPrefix=2
            - id: inventory-service
              uri: ${app.inventory-service}
              predicates:
                - Path=${app.prefix}/inventory/**
              filters:
                - StripPrefix=2
            - id: order-service
              uri: ${app.order-service}
              predicates:
                - Path=${app.prefix}/order/**
              filters:
                - StripPrefix=2