spring:
  application:
    name: product-service
  mongodb:
    uri: mongodb://root:root@localhost:27017/product-service?authSource=admin
server:
  port: 8082
  servlet:
    context-path: /product
app:
  file-service: http://localhost:8081/file

